### ISSUE TITLE
Lens self notification and stopped getting notifications all together in the last week of October 

### ISSUE THREAD

**Issue by richajoshi123** [ethereum-push-notification-service/push-showrunners-framework#8]
A user (paulburke.lens) reported the following issues
- received self notifications i.e. when they left a comment they received a notification 
- Notifications all together stopped in last week of October

Message from the Paul-
I’m not exactly sure. When the lens integration was announced I subscribed, and I’ve only received notifications when I actually leave a comment somewhere, not one for comments on my posts. I stopped getting them all together in the last week of October.

**Comment by richajoshi123** [comment]
Post on Lenster with 1 comment
<img width="811" alt="Screen Shot 2022-11-17 at 12 08 04 AM" src="https://user-images.githubusercontent.com/47238805/202283783-47245e5b-669b-4f44-a78f-28e173117227.png">

Notification on Push dApp - 2 duplicate notifications received
<img width="1555" alt="Screen Shot 2022-11-17 at 12 06 06 AM" src="https://user-images.githubusercontent.com/47238805/202283883-46f8cd80-9148-4912-af05-607b74611d2d.png">

Notification on Push mobile app - 3 duplicate notifications received
![File](https://user-images.githubusercontent.com/47238805/202284144-68b45fb8-3e7a-4641-bfd5-6937402cee30.jpg)

@prathmeshkhandelwal1 @aiswaryawalter @zaryab2000

**Comment by pranshurastogi** [comment]
<img width="1142" alt="Screenshot 2022-11-18 at 9 09 59 PM" src="https://user-images.githubusercontent.com/12568291/202743640-239e17f5-f1e2-4d36-91e0-05d2b3f07f82.png">

![IMG_4551](https://user-images.githubusercontent.com/12568291/202743841-425c1df7-e9cd-4b9d-b339-ffbb86c37e8f.png)

Use case tested -
* When someone comments on the post
* When user comments in his/her post itself.

Both are working fine !! Screenshot is attached.

**Comment by richajoshi123** [comment]
reopening the issue. let's close it after user confirmation.

**Comment by aeyshubh** [comment]
closing this as this seems to be resolved.
